preset: symfony

risky: true

linting: false

enabled:
    #- ordered_class_elements
    - ordered_imports
    - phpdoc_order
    - short_array_syntax
    - strict_param
    #- declare_strict_types

finder:
    path:
        - 'src/'
        - 'tests/'
    not-path:
        - 'Fixtures'
