language: php

matrix:
    include:
        - php: 7.0
        # Use the newer stack for HHVM as HHVM does not support Precise anymore since a long time and so Precise has an outdated version
        #- php: hhvm-3.12
        #  sudo: required
        #  dist: trusty
        #  group: edge
        - php: 7.0
          env: DEPENDENCIES='low'
        - php: 7.1
          env: DEPENDENCIES='dev'
    allow_failures:
        - env: DEPENDENCIES='dev'
    fast_finish: true

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

install:
    - export SYMFONY_DEPRECATIONS_HELPER=strong
    - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [ "$DEPENDENCIES" != "low" ]; then travis_retry composer update; fi;
    - if [ "$DEPENDENCIES" == "low" ]; then travis_retry composer update --prefer-lowest; fi;

script:
    - vendor/bin/phpunit --configuration phpunit.xml.dist --verbose
