language: php

sudo: false

branches:
    only:
        - master

matrix:
    include:
        - php: '7.1'
        - php: '7.1'
          env: deps='low'
        #- php: '7.1'
        #  env: deps='dev'
        # Use the newer stack for HHVM as HHVM does not support Precise anymore since a long time and so Precise has an outdated version
        #- php: hhvm-3.12
        #  sudo: required
        #  dist: trusty
        #  group: edge
    allow_failures:
        - env: deps='dev'

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - export SYMFONY_PHPUNIT_REMOVE="symfony/yaml"
    - export SYMFONY_PHPUNIT_VERSION=6.0
    - export SYMFONY_DEPRECATIONS_HELPER=strict

install:
    - if [[ ! $deps ]]; then composer update --prefer-dist --no-progress --no-suggest --ansi; fi
    - if [[ $deps = 'dev' ]]; then composer config minimum-stability dev && composer update --prefer-dist --no-progress --no-suggest --ansi ; fi
    - if [[ $deps = 'low' ]]; then composer update --prefer-dist --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi; fi

script:
    - vendor/bin/simple-phpunit --verbose
